---
apiVersion: v1
kind: Template
metadata:
  name: sbt-s2i
  annotations:
    displayName: Scala SBT S2I
    description: Build and run Scala and Java applications using SBT
    iconClass: icon-scala
    tags: builder,scala,sbt

parameters:
  - name: SBT_VERSION
    displayName: SBT Version
    description: Version of SBT to use (eg. 0.13.16).
    value: 0.13.16
    required: true

  - name: SCALA_VERSION
    displayName: Scala Version
    description: Version of Scala to use (eg. 2.12.5).
    value: 2.12.5
    required: true

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: sbt-s2i
      annotations:
        iconClass: icon-scala
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations:
          description: Build and run Scala and Java applications using SBT
          iconClass: icon-scala
          openshift.io/display-name: SBT
          openshift.io/provider-display-name: https://github.com/jw3/sbt-s2i
          sampleRepo: https://github.com/theiterators/akka-http-microservice
          supports: sbt,java,scala
          tags: builder,java,scala
          version: ${SBT_VERSION}-${SCALA_VERSION}
        from:
          kind: DockerImage
          name: jwiii/sbt-s2i:${SBT_VERSION}-${SCALA_VERSION}
        importPolicy: {}
        name: ${SBT_VERSION}-${SCALA_VERSION}
        referencePolicy:
          type: Source
