apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Build and run Scala and Java applications using SBT
    iconClass: icon-scala
    openshift.io/display-name: SBT
  generation: 4
  name: sbt
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Scala and Java applications using SBT
      iconClass: icon-scala
      openshift.io/display-name: SBT
      openshift.io/provider-display-name: FFM Nexus
      sampleRepo: https://github.com/theiterators/akka-http-microservice
      supports: sbt:1.4.1,java,scala
      tags: builder,java,scala
      version: "1.4.1"
    from:
      kind: DockerImage
      name: nexus-openshift-poc.ffm-poc.mp.cmscloud.local:8083/sbt-s2i:1.4.1
    generation: 1
    importPolicy: {}
    name: "1.4.1"
    referencePolicy:
      type: Source
